apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_SERVICE: postgres
  POSTGRES_DB: shopping
---
apiVersion: v1
kind: Secret
metadata:
  name: db-security
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
